var searchData=
[
  ['o_20setting_20in_20standby_20shutdown_20mode_0',['GPIO bit number for I/O setting in standby/shutdown mode',['../group___p_w_r_ex___g_p_i_o___bit___number.html',1,'']]],
  ['of_20stop_20bits_1',['UART Number of Stop Bits',['../group___u_a_r_t___stop___bits.html',1,'']]],
  ['of_20unitary_20conversion_20or_20sequence_20conversions_2',['ADC sequencer end of unitary conversion or sequence conversions',['../group___a_d_c___e_o_c_selection.html',1,'']]],
  ['offset_20number_3',['ADC instance - Offset number',['../group___a_d_c___h_a_l___e_c___o_f_f_s_e_t___n_b.html',1,'']]],
  ['offset_20sign_4',['ADC Extended Offset Sign',['../group___a_d_c_ex___offset_sign.html',1,'']]],
  ['offstate_20selection_20for_20idle_20mode_20state_5',['TIM OSSI OffState Selection for Idle mode state',['../group___t_i_m___o_s_s_i___off___state___selection__for___idle__mode__state.html',1,'']]],
  ['offstate_20selection_20for_20run_20mode_20state_6',['TIM OSSR OffState Selection for Run mode state',['../group___t_i_m___o_s_s_r___off___state___selection__for___run__mode__state.html',1,'']]],
  ['on_20conversion_20data_7',['ADC group regular - Overrun behavior on conversion data',['../group___a_d_c___h_a_l___e_c___r_e_g___o_v_r___d_a_t_a___b_e_h_a_v_i_o_r.html',1,'']]],
  ['on_20gpio_8',['Fast-mode Plus on GPIO',['../group___s_y_s_c_f_g___fast_mode_plus___g_p_i_o.html',1,'']]],
  ['on_20rdp_20level_20type_9',['FLASH Option Bytes PCROP On RDP Level Type',['../group___f_l_a_s_h___o_b___p_c_r_o_p___r_d_p.html',1,'']]],
  ['on_20reset_20type_10',['FLASH Option Bytes User CCMSRAM Erase On Reset Type',['../group___f_l_a_s_h___o_b___u_s_e_r___c_c_m_s_r_a_m___r_s_t.html',1,'']]],
  ['on_20rx_20error_11',['UART Advanced Feature DMA Disable On Rx Error',['../group___u_a_r_t___d_m_a___disable__on___rx___error.html',1,'']]],
  ['on_20shutdown_12',['FLASH Option Bytes User Reset On Shutdown',['../group___f_l_a_s_h___o_b___u_s_e_r__n_r_s_t___s_h_u_t_d_o_w_n.html',1,'']]],
  ['on_20standby_13',['On Standby',['../group___f_l_a_s_h___o_b___u_s_e_r___i_w_d_g___s_t_a_n_d_b_y.html',1,'FLASH Option Bytes User IWDG Mode On Standby'],['../group___f_l_a_s_h___o_b___u_s_e_r__n_r_s_t___s_t_a_n_d_b_y.html',1,'FLASH Option Bytes User Reset On Standby']]],
  ['on_20stop_14',['On Stop',['../group___f_l_a_s_h___o_b___u_s_e_r___i_w_d_g___s_t_o_p.html',1,'FLASH Option Bytes User IWDG Mode On Stop'],['../group___f_l_a_s_h___o_b___u_s_e_r__n_r_s_t___s_t_o_p.html',1,'FLASH Option Bytes User Reset On Stop']]],
  ['one_20bit_20sampling_20method_15',['UART One Bit Sampling Method',['../group___u_a_r_t___one_bit___sampling.html',1,'']]],
  ['one_20pulse_20functions_16',['One Pulse functions',['../group___t_i_m_ex___exported___functions___group4.html',1,'Extended Timer Complementary One Pulse functions'],['../group___t_i_m___exported___functions___group5.html',1,'TIM One Pulse functions']]],
  ['one_20pulse_20mode_17',['TIM One Pulse Mode',['../group___t_i_m___one___pulse___mode.html',1,'']]],
  ['opamp_20aliased_20defines_20maintained_20for_20legacy_20purpose_18',['HAL OPAMP Aliased Defines maintained for legacy purpose',['../group___h_a_l___o_p_a_m_p___aliased___defines.html',1,'']]],
  ['opamp_20aliased_20macros_20maintained_20for_20legacy_20purpose_19',['HAL OPAMP Aliased Macros maintained for legacy purpose',['../group___h_a_l___o_p_a_m_p___aliased___macros.html',1,'']]],
  ['operation_20functions_20',['operation functions',['../group___e_x_t_i___exported___functions___group2.html',1,'IO operation functions'],['../group___g_p_i_o___exported___functions___group2.html',1,'IO operation functions'],['../group___u_a_r_t___exported___functions___group2.html',1,'IO operation functions']]],
  ['option_20bit_21',['FLASH Option Bytes User nBOOT0 option bit',['../group___f_l_a_s_h___o_b___u_s_e_r__n_b_o_o_t0.html',1,'']]],
  ['option_20bytes_20pcrop_20on_20rdp_20level_20type_22',['FLASH Option Bytes PCROP On RDP Level Type',['../group___f_l_a_s_h___o_b___p_c_r_o_p___r_d_p.html',1,'']]],
  ['option_20bytes_20read_20protection_23',['FLASH Option Bytes Read Protection',['../group___f_l_a_s_h___o_b___read___protection.html',1,'']]],
  ['option_20bytes_20type_24',['FLASH Option Bytes Type',['../group___f_l_a_s_h___o_b___type.html',1,'']]],
  ['option_20bytes_20user_20boot1_20type_25',['FLASH Option Bytes User BOOT1 Type',['../group___f_l_a_s_h___o_b___u_s_e_r__n_b_o_o_t1.html',1,'']]],
  ['option_20bytes_20user_20bor_20level_26',['FLASH Option Bytes User BOR Level',['../group___f_l_a_s_h___o_b___u_s_e_r___b_o_r___l_e_v_e_l.html',1,'']]],
  ['option_20bytes_20user_20ccmsram_20erase_20on_20reset_20type_27',['FLASH Option Bytes User CCMSRAM Erase On Reset Type',['../group___f_l_a_s_h___o_b___u_s_e_r___c_c_m_s_r_a_m___r_s_t.html',1,'']]],
  ['option_20bytes_20user_20internal_20reset_20holder_20bit_28',['FLASH Option Bytes User internal reset holder bit',['../group___f_l_a_s_h___o_b___u_s_e_r___i_n_t_e_r_n_a_l___r_e_s_e_t___h_o_l_d_e_r.html',1,'']]],
  ['option_20bytes_20user_20iwdg_20mode_20on_20standby_29',['FLASH Option Bytes User IWDG Mode On Standby',['../group___f_l_a_s_h___o_b___u_s_e_r___i_w_d_g___s_t_a_n_d_b_y.html',1,'']]],
  ['option_20bytes_20user_20iwdg_20mode_20on_20stop_30',['FLASH Option Bytes User IWDG Mode On Stop',['../group___f_l_a_s_h___o_b___u_s_e_r___i_w_d_g___s_t_o_p.html',1,'']]],
  ['option_20bytes_20user_20iwdg_20type_31',['FLASH Option Bytes User IWDG Type',['../group___f_l_a_s_h___o_b___u_s_e_r___i_w_d_g___s_w.html',1,'']]],
  ['option_20bytes_20user_20nboot0_20option_20bit_32',['FLASH Option Bytes User nBOOT0 option bit',['../group___f_l_a_s_h___o_b___u_s_e_r__n_b_o_o_t0.html',1,'']]],
  ['option_20bytes_20user_20nrst_20mode_20bit_33',['FLASH Option Bytes User NRST mode bit',['../group___f_l_a_s_h___o_b___u_s_e_r___n_r_s_t___m_o_d_e.html',1,'']]],
  ['option_20bytes_20user_20reset_20on_20shutdown_34',['FLASH Option Bytes User Reset On Shutdown',['../group___f_l_a_s_h___o_b___u_s_e_r__n_r_s_t___s_h_u_t_d_o_w_n.html',1,'']]],
  ['option_20bytes_20user_20reset_20on_20standby_35',['FLASH Option Bytes User Reset On Standby',['../group___f_l_a_s_h___o_b___u_s_e_r__n_r_s_t___s_t_a_n_d_b_y.html',1,'']]],
  ['option_20bytes_20user_20reset_20on_20stop_36',['FLASH Option Bytes User Reset On Stop',['../group___f_l_a_s_h___o_b___u_s_e_r__n_r_s_t___s_t_o_p.html',1,'']]],
  ['option_20bytes_20user_20software_20boot0_37',['FLASH Option Bytes User Software BOOT0',['../group___f_l_a_s_h___o_b___u_s_e_r__n_s_w_b_o_o_t0.html',1,'']]],
  ['option_20bytes_20user_20sram_20parity_20check_20type_38',['FLASH Option Bytes User SRAM Parity Check Type',['../group___f_l_a_s_h___o_b___u_s_e_r___s_r_a_m___p_e.html',1,'']]],
  ['option_20bytes_20user_20type_39',['FLASH Option Bytes User Type',['../group___f_l_a_s_h___o_b___u_s_e_r___type.html',1,'']]],
  ['option_20bytes_20user_20wwdg_20type_40',['FLASH Option Bytes User WWDG Type',['../group___f_l_a_s_h___o_b___u_s_e_r___w_w_d_g___s_w.html',1,'']]],
  ['or_203_41',['TIM Group Channel 5 and Channel 1, 2 or 3',['../group___t_i_m___group___channel5.html',1,'']]],
  ['or_20differential_20ending_42',['Channel - Single or differential ending',['../group___a_d_c___h_a_l___e_c___c_h_a_n_n_e_l___s_i_n_g_l_e___d_i_f_f___e_n_d_i_n_g.html',1,'']]],
  ['or_20disabled_20status_43',['or Disabled Status',['../group___r_c_c___a_h_b1___peripheral___clock___enable___disable___status.html',1,'AHB1 Peripheral Clock Enabled or Disabled Status'],['../group___r_c_c___a_h_b1___clock___sleep___enable___disable___status.html',1,'AHB1 Peripheral Clock Sleep Enabled or Disabled Status'],['../group___r_c_c___a_h_b2___clock___enable___disable___status.html',1,'AHB2 Peripheral Clock Enabled or Disabled Status'],['../group___r_c_c___a_h_b2___clock___sleep___enable___disable___status.html',1,'AHB2 Peripheral Clock Sleep Enabled or Disabled Status'],['../group___r_c_c___a_h_b3___clock___enable___disable___status.html',1,'AHB3 Peripheral Clock Enabled or Disabled Status'],['../group___r_c_c___a_h_b3___clock___sleep___enable___disable___status.html',1,'AHB3 Peripheral Clock Sleep Enabled or Disabled Status'],['../group___r_c_c___a_p_b1___clock___enable___disable___status.html',1,'APB1 Peripheral Clock Enabled or Disabled Status'],['../group___r_c_c___a_p_b1___clock___sleep___enable___disable___status.html',1,'APB1 Peripheral Clock Sleep Enabled or Disabled Status'],['../group___r_c_c___a_p_b2___clock___enable___disable___status.html',1,'APB2 Peripheral Clock Enabled or Disabled Status'],['../group___r_c_c___a_p_b2___clock___sleep___enable___disable___status.html',1,'APB2 Peripheral Clock Sleep Enabled or Disabled Status']]],
  ['or_20sequence_20conversions_44',['ADC sequencer end of unitary conversion or sequence conversions',['../group___a_d_c___e_o_c_selection.html',1,'']]],
  ['oscillator_20drive_20capability_45',['LSE oscillator drive capability',['../group___r_c_c___l_l___e_c___l_s_e_d_r_i_v_e.html',1,'']]],
  ['oscillator_20type_46',['Oscillator Type',['../group___r_c_c___oscillator___type.html',1,'']]],
  ['oscillator_20values_20adaptation_47',['Oscillator Values adaptation',['../group___r_c_c___l_l___e_c___o_s_c___v_a_l_u_e_s.html',1,'']]],
  ['ossi_20offstate_20selection_20for_20idle_20mode_20state_48',['TIM OSSI OffState Selection for Idle mode state',['../group___t_i_m___o_s_s_i___off___state___selection__for___idle__mode__state.html',1,'']]],
  ['ossr_20offstate_20selection_20for_20run_20mode_20state_49',['TIM OSSR OffState Selection for Run mode state',['../group___t_i_m___o_s_s_r___off___state___selection__for___run__mode__state.html',1,'']]],
  ['out_20value_50',['UART polling-based communications time-out value',['../group___u_a_r_t___time_out___value.html',1,'']]],
  ['output_51',['PLL Clock Output',['../group___r_c_c___p_l_l___clock___output.html',1,'']]],
  ['output_20compare_20and_20pwm_20modes_52',['TIM Output Compare and PWM Modes',['../group___t_i_m___output___compare__and___p_w_m__modes.html',1,'']]],
  ['output_20compare_20functions_53',['Output Compare functions',['../group___t_i_m_ex___exported___functions___group2.html',1,'Extended Timer Complementary Output Compare functions'],['../group___t_i_m___exported___functions___group2.html',1,'TIM Output Compare functions']]],
  ['output_20compare_20idle_20state_54',['Output Compare Idle State',['../group___t_i_m___output___compare___n___idle___state.html',1,'TIM Complementary Output Compare Idle State'],['../group___t_i_m___output___compare___idle___state.html',1,'TIM Output Compare Idle State']]],
  ['output_20compare_20polarity_55',['Output Compare Polarity',['../group___t_i_m___output___compare___n___polarity.html',1,'TIM Complementary Output Compare Polarity'],['../group___t_i_m___output___compare___polarity.html',1,'TIM Output Compare Polarity']]],
  ['output_20compare_20state_56',['Output Compare State',['../group___t_i_m___output___compare___n___state.html',1,'TIM Complementary Output Compare State'],['../group___t_i_m___output___compare___state.html',1,'TIM Output Compare State']]],
  ['output_20enable_57',['TIM Automatic Output Enable',['../group___t_i_m___a_o_e___bit___set___reset.html',1,'']]],
  ['output_20fast_20state_58',['TIM Output Fast State',['../group___t_i_m___output___fast___state.html',1,'']]],
  ['over_20sampling_59',['UART Over Sampling',['../group___u_a_r_t___over___sampling.html',1,'']]],
  ['overrun_20behavior_20on_20conversion_20data_60',['ADC group regular - Overrun behavior on conversion data',['../group___a_d_c___h_a_l___e_c___r_e_g___o_v_r___d_a_t_a___b_e_h_a_v_i_o_r.html',1,'']]],
  ['overrun_20disable_61',['UART Advanced Feature Overrun Disable',['../group___u_a_r_t___overrun___disable.html',1,'']]],
  ['oversampling_20data_20shift_62',['Oversampling - Data shift',['../group___a_d_c___h_a_l___e_c___o_v_s___s_h_i_f_t.html',1,'']]],
  ['oversampling_20discontinuous_20mode_63',['Oversampling - Discontinuous mode',['../group___a_d_c___h_a_l___e_c___o_v_s___d_i_s_c_o_n_t___m_o_d_e.html',1,'']]],
  ['oversampling_20oversampling_20scope_20for_20adc_20group_20regular_64',['Oversampling - Oversampling scope for ADC group regular',['../group___a_d_c___h_a_l___e_c___o_v_s___s_c_o_p_e___r_e_g.html',1,'']]],
  ['oversampling_20ratio_65',['Oversampling - Ratio',['../group___a_d_c___h_a_l___e_c___o_v_s___r_a_t_i_o.html',1,'']]],
  ['oversampling_20scope_20for_20adc_20group_20regular_66',['Oversampling - Oversampling scope for ADC group regular',['../group___a_d_c___h_a_l___e_c___o_v_s___s_c_o_p_e___r_e_g.html',1,'']]]
];
